src/StatsBundle/Entity/Skill.php
<?php

namespace StatsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Skill
 * @ORM\Table(name="oc_skill")
 * @ORM\Entity
 */
class Skill
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Skill
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    public function getUsers()
    {
        return array();
    }
}

src/StatsBundle/Form/SkillType.php
<?php

namespace StatsBundle\Form;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SkillType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('save', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'StatsBundle\Entity\Skill'
        ));
    }
}

src/StatsBundle/Resources/views/Skill/add.html.twig
{% extends "StatsBundle::layout.html.twig" %}

{% block title %}
    Créer une annonce - {{ parent() }}
{% endblock %}

{% block sms_body %}

    <h2>Créer une annonce</h2>

    {{ include("StatsBundle:Skill:form.html.twig") }}

    <p>
        <a href="{{ path('sms_home') }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à l'accueil
        </a>
    </p>

{% endblock %}

src/StatsBundle/Resources/views/Skill/delete.html.twig
{% extends "StatsBundle::layout.html.twig" %}

{% block title %}
    Supprimer une annonce - {{ parent() }}
{% endblock %}

{% block sms_body %}

    <h2>Supprimer une compétence</h2>

    <p>
        Etes-vous certain de vouloir supprimer cette compétence "{{ skill.name}}" ?
    </p>

    {# On met l'id de l'annonce dans la route de l'action du formulaire #}
    <form action="{{ path('sms_delete_skill', {'id': skill.id}) }}" method="post">
        <a href="{{ path('sms_view_skill', {'id': skill.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à l'annonce
        </a>
        {# Ici j'ai écrit le bouton de soumission à la main #}
        <input type="submit" value="Supprimer" class="btn btn-danger" />
        {# Ceci va générer le champ CSRF #}
        {{ form_rest(form) }}
    </form>

{% endblock %}

src/StatsBundle/Resources/views/Skill/edit.html.twig
{% extends "StatsBundle::layout.html.twig" %}

{% block title %}
    Modifier une compétence- {{ parent() }}
{% endblock %}

{% block sms_body %}

    <h2>Modifier une compétence</h2>

    {{ include("StatsBundle:Skill:form.html.twig") }}

    <p>
        Vous éditez une compétence déjà existante.
    </p>

    <p>
        <a href="{{ path('sms_view_skill', {'id': skill.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à la compétence
        </a>
    </p>

{% endblock %}

src/StatsBundle/Resources/views/Skill/form.html.twig
<h3>Formulaire d'annonce</h3>

<div class="well">
    {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

    {# Les erreurs générales du formulaire. #}
    {{ form_errors(form) }}

    {# Génération manuelle et éclatée : #}
    <div class="form-group">
        {# Génération du label. #}
        {{ form_label(form.name, "Compétence", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

        {# Affichage des erreurs pour ce champ précis. #}
        {{ form_errors(form.name) }}

        <div class="col-sm-10">
            {# Génération de l'input. #}
            {{ form_widget(form.name, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>

    {# Pour le bouton, pas de label ni d'erreur, on affiche juste le widget #}
    {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}

    {# Génération automatique des champs pas encore écrits.
       Dans cet exemple, ce serait le champ CSRF (géré automatiquement par Symfony !)
       et tous les champs cachés (type « hidden »). #}
    {{ form_rest(form) }}

    {# Fermeture de la balise <form> du formulaire HTML #}
    {{ form_end(form) }}
</div>

src/StatsBundle/Resources/views/Skill/index.html.twig
{% extends "Statsundle::layout.html.twig" %}

{% block title %}
    Accueil - {{ parent() }}
{% endblock %}

{% block sms_body %}

    <h2>Liste des compétences</h2>

    <ul>
        {% for skill in listSkills %}
            <li>
                <a href="{{ path('sms_view', {'skill': skill}) }}">
                    {{ skill.name}}
                </a>
            </li>
        {% else %}
            <li>Pas (encore !) de compétences</li>
        {% endfor %}
    </ul>
    <ul class="pagination">
        {# On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b #}
        {% for p in range(1, nbPages) %}
            <li{% if p == page %} class="active"{% endif %}>
                <a href="{{ path('sms_home', {'page': p}) }}">{{ p }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

src/StatsBundle/Resources/views/Skill/list.html.twig
{% extends "StatsBundle::layout.html.twig" %}

{% block title %}
    Accueil - {{ parent() }}
{% endblock %}

{% block sms_body %}

    <h2>Liste des compétences</h2>

    <ul>
        {% for skill in listSkills %}
            <li>
                <a href="{{ path('sms_view_skill', {'id': skill.id}) }}">
                    {{ skill.name}}
                </a>
            </li>
        {% else %}
            <li>Pas (encore !) de compétences</li>
        {% endfor %}
    </ul>
    <a href="{{ path('sms_add_skill') }}">Ajouter une compétence</a>
    <ul class="pagination">
        {# On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b #}
        {% for p in range(1, nbPages) if p > 0 %}
            <li{% if p == page %} class="active"{% endif %}>
                <a href="{{ path('sms_home', {'page': p}) }}">{{ p }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

src/StatsBundle/Resources/views/Skill/menu.html.twig
<ul class="nav nav-pills nav-stacked">
    {% for skill in listSkills %}
        <li>
            <a href="{{ path('sms_view_skill', {'skill': skill}) }}">
                {{ skill.name }}
            </a>
        </li>
    {% endfor %}
</ul>

src/StatsBundle/Resources/views/Skill/view.html.twig
{% extends "StatsBundle::layout.html.twig" %}

{% block title %}
    Compétence - {{ parent() }}
{% endblock %}

{% block sms_body %}

    <div class="row">
        <div class="col-sm-8">
            <h2>{{ skill.name}}</h2>
        </div>
    </div>

    <p>
        <a href="{{ path('sms_home') }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à la liste
        </a>
        <a href="{{ path('sms_edit_skill', {'id': skill.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-edit"></i>
            Modifier la compétence
        </a>
        <a href="{{ path('sms_delete_skill', {'id': skill.id}) }}" class="btn btn-danger">
            <i class="glyphicon glyphicon-trash"></i>
            Supprimer la compétence
        </a>
    </p>
    {% if skill.users is not empty %}
        <p>
            Cette compétence est utilisée par les joueurs suivants :
            {% for player in skill.users %}
                {{ user.name }}{% if not loop.last %}, {% endif %}
            {% endfor %}
        </p>
    {% endif %}

{% endblock %}